FROM alpine

RUN apk add --no-cache bash git nginx uwsgi uwsgi-python py2-pip \
	&& pip2 install --upgrade pip \
	&& pip2 install flask

WORKDIR /app

COPY . /app
RUN pip install -r /app/requirements/dev.txt

ENV FLASK_APP /app/run.py
#ENV FLASK_DEBUG 1

EXPOSE 5000
CMD ["flask", "run", "--host","0.0.0.0" ]
